apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: calculator 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calculator 
    spec:
      containers:
        - name: calculator 
          image: devopsbuild2019.azurecr.io/calculator 
          ports:
          - containerPort: 3000